### PR TITLE
[ Enhance ]: Implement dynamic board naming on creation and display board names in delete messages

### PR DESCRIPTION
**Pull request by brf153**
Initial Pic:
Screenshot from 2023-12-16 12-29-30

After making two boards:
Screenshot from 2023-12-16 12-30-47

### CODE REVIEW

**Comment by brf153** [comment]
@CulturalProfessor I have added pics for reference cause I am having some screen error in my laptop. I don't know why everything is black in the lower half of the screen of my laptop. I will try to fix this.

**Comment by brf153** [comment]
By the way I have made this pr cause before making the search functionality, I want to make sure that we are rendering different names for each board. In the search functionality I would add `/whiteboard search {boardname}` instead of {boardID} such that it is easier for peeps to search for board.

**Comment by brf153** [comment]
One more change

Screenshot from 2023-12-16 12-46-44

**Comment by brf153** [comment]
Rendering the boardName which has been deleted. It would be useful cause the room members would get to know that a specific board has been deleted.

**Comment by brf153** [comment]
You can see the change that above the red line there was the previous message that we were rendering when deleting the board. Then below the red line, we have the new delete message that we would render after deleting the board.

**Comment by CulturalProfessor** [comment]
ok it's more helpful for users now , good work :clap:

**Pull request merged**
