### PR TITLE
Feat: Adding search functionality

### PR DESCRIPTION
**Pull request by brf153**
Adding the search functionality.

### CODE REVIEW

**Comment by CulturalProfessor** [comment]
https://github.com/markboard-io/markboard/pull/42 check this out I implemented something similar in markboard also so it will help you out

**Comment by brf153** [comment]
https://github.com/RocketChat/Apps.Whiteboard/assets/107868772/6a6320bb-7ec0-45d6-9295-cf7d30b1f282

**Comment by brf153** [comment]
@CulturalProfessor please check this work. I have added the `/whiteboard search {boardName}` command.

**Comment by CulturalProfessor** [comment]
ok that's really cool :tada:

**Comment by Sumitwarrior7** [comment]
This search functionality is creating multiple whiteboards with same name which is not desired, this is affecting other functionalities as well 

So please check it once again 
@brf153

**Comment by brf153** [comment]
@Sumitwarrior7 Actually it is not creating multiple whiteboards but a replica of the original whiteboard. Also, the replica was being made because after changing the name from Untitled Whiteboard to some other name, I was getting two objects in an array which means that a replica was being created after changing the name only. According to the current situation, I made the most suitable changes for the search list command. Never mind, I will make certain changes in the coming days to correct it.

**Comment by CulturalProfessor** [comment]
> @Sumitwarrior7 Actually it is not creating multiple whiteboards but a replica of the original whiteboard. Also, multiple boards were being made because after changing the name from Untitled Whiteboard to some other name, I was getting two objects in an array which means that multiple boards were being created after changing the name only. According to the current situation, I made the most suitable changes for the search list command. Never mind, I will make certain changes in the coming days to correct it.

@brf153 you need to clarify any problems you are facing like this before pr is merged. great work @Sumitwarrior7 pointing this out

**Comment by CulturalProfessor** [comment]
@Sumitwarrior7 check if it's working fine now

**Comment by brf153** [comment]
@CulturalProfessor I actually checked it. You can actually see it by yourself. When we search the board, I have made the functionality that the board will be rendered. But the board will be a replica of the original board and not the same board. If we make any changes to the replica board then only the original board will get affected. The issue which he is stating is related to name change. When we change name then we expect that the original board's details will be replaced by the new board's details but it was not happening. Rather the new board is stored along with the original board and so two boards were being created. I was working on this issue and thought of fixing it in the next pr.

**Pull request merged**
