### PR TITLE
[ Fix ] : Board renaming bug in DM

### PR DESCRIPTION
**Pull request by Sumitwarrior7**
The description of issue : #36

Issue is solved, for you reference you can see below video :

https://github.com/RocketChat/Apps.Whiteboard/assets/108853577/57f70873-856f-45bf-a56d-cece504521c9

### CODE REVIEW

**Comment by CulturalProfessor** [comment]
@Sumitwarrior7 can you check if it works if we don't change privacy ?

**Comment by Sumitwarrior7** [comment]
If you are saying without changing privacy that is maybe you want to say that we are trying to change only boardname without changing the board status i.e., private or public 
So, yeah it works

If i misunderstood you, then please elaborate what you want to say, i will record a video regarding it if my pr resolves that , if not i will solve it .

**Comment by CulturalProfessor** [comment]
> If you are saying without changing privacy that is maybe you want to say that we are trying to change only boardname without changing the board status i.e., private or public So, yeah it works
> 
> If i misunderstood you, then please elaborate what you want to say, i will record a video regarding it if my pr resolves that , if not i will solve it .

ok cool, https://github.com/RocketChat/Apps.Whiteboard/issues/36#issuecomment-1846003447 see this to understand proper flow for app

**Comment by CulturalProfessor** [comment]
yeah cool , LGTM !!

**Comment by Sumitwarrior7** [comment]
closes #36

**Pull request merged**
