### PR TITLE
[ Feat ]: Board modifications permission granted only to admin and creator

### LINKED ISSUE #71: Admin only rights for editing and deleting boards
Only the room admin should be allowed to delete and edit the boards in the room along with the user who created the board. The other users can do the same only when granted permission by the admin or the creator.

### PR DESCRIPTION
**Pull request by brf153**
This issue closes #71

## How I will proceed:

- First when user creates a board then the roles should change to owner.
- Second, make a persistance or find a persistance which contains the data that contains which user created which board. Meaning which messageId belongs to which user.
- Then make a function which checks whether the user currently accessing has the rights or not. Check the role whether it is admin or owner.
- If the role does not contain admin or owner then notify(checkboard type) the user to ask for permission. If he says yes then notify the admin and the user to give the permission.
- If they allow then first add the user to owner of that board then notify the user that access has been granted to the `${boardName}`

### CODE REVIEW

**Comment by brf153** [comment]
Recent Changes:

1. Added room admin to the boardOwner array.
2. Implemented a permission block for boardOwners to respond.
3. When they grant permission, the user who requested it will be added to the boardOwner array.
4. A message is sent to the user who requested permission, confirming 'Permission granted'.

**Comment by brf153** [comment]
Recent changes:
1. All the required changes have been made.
2. Just the board edit button changes are remaining

**Comment by brf153** [comment]
https://github.com/RocketChat/Apps.Whiteboard/assets/107868772/4eb53f08-dcb4-41c2-b78f-e226e13724a3

**Comment by brf153** [comment]
@CulturalProfessor Please review these changes. Also, I need some help. 

1. How to change or delete the notify messages? The permission notification which I am sending to the boardOwner which states `bhandari.devaansh wants to edit **kio**` does not return a messageId. How will I modify it?

2. Also, how will I stop the user from editing the board? When I click on the edit button, the board opens directly without any action being involved in between.

**Comment by brf153** [comment]
@CulturalProfessor Instead of directly opening the board when the user clicks on the 'Edit Board' button, we can enhance the user experience by first prompting them with a confirmation message to verify whether they genuinely wish to edit the board. This approach allows for an authorization check before rendering the board data. If the user confirms their intention, the board URL will be passed for rendering. However, if the user lacks the necessary permissions, we will display a message indicating that permission is not allowed and provide an option for requesting access. This method ensures a more controlled and user-friendly interaction.

**Comment by CulturalProfessor** [comment]
> @CulturalProfessor Instead of directly opening the board when the user clicks on the 'Edit Board' button, we can enhance the user experience by first prompting them with a confirmation message to verify whether they genuinely wish to edit the board. This approach allows for an authorization check before rendering the board data. If the user confirms their intention, the board URL will be passed for rendering. However, if the user lacks the necessary permissions, we will display a message indicating that permission is not allowed and provide an option for requesting access. This method ensures a more controlled and user-friendly interaction.

Yeah this will be a good approach

**Comment by brf153** [comment]
@CulturalProfessor I am kind of changing the approach. Initially rather than showing the buttons for settings, edit and delete, I will show a button for options. When the user clicks on the button, I will ask for permission whether the user wants to edit the board or not. If the user clicks on edit then I will show the button which will contain all the options. In this way, if the user is not the board owner or the room admin then rather than showing the edit board option message, I will show the ask for permission message.

https://github.com/RocketChat/Apps.Whiteboard/assets/107868772/ef5c8f62-a6a5-4794-bfdb-f91b1a4a890b

**Comment by brf153** [comment]
Also, the message will be replaced by a notification which only the user with the permission will be able to see.

**Comment by CulturalProfessor** [comment]
Great work @brf153 :tada:

**Comment by brf153** [comment]
@CulturalProfessor Thank you! I also appreciate your time in reviewing such a large pull request.

**Pull request merged**
