### PR TITLE
[ Feat ] : Makefile for setup and improved the readme file

### PR DESCRIPTION
**Pull request by brf153**
From:
Screenshot from 2023-12-13 13-22-36

To:
Screenshot from 2023-12-13 14-07-43

### CODE REVIEW

**Comment by brf153** [comment]
@CulturalProfessor I think the changes I have made looks better

**Comment by CulturalProfessor** [comment]
@brf153 update contributors section spelling also

**Comment by brf153** [comment]
@CulturalProfessor I did not get it. Which spelling am I supposed to update?

**Comment by CulturalProfessor** [comment]
image

**Comment by brf153** [comment]
lol

**Comment by brf153** [comment]
@CulturalProfessor done

**Pull request merged**
