### PR TITLE
Feat: handle delete added but not sure on how to proceed(few errors present, review required)

### PR DESCRIPTION
**Pull request by smitjiwani**
## Proposed Changes

I have made changes to the ./Apps.Whiteboard/whiteboard/lib/commandUtility.ts. I'm still a little unsure about which methods are to be called. your help and guidance would be really valuable for my learning and me solving the issue eventually. Please provide a review @CulturalProfessor.

## Related issues

#27

### CODE REVIEW

**Comment by Sumitwarrior7** [comment]
@smitjiwani For your kind info, let me tell you i have been assigned this issue and i have already completed it some days before.
But not created a pr for it because it was a continuation to the this pr #46 .
So when this #46 pr will be merged then only i can create the pr for delete command so that no issue arises.
As @CulturalProfessor is busy, thats why the above pr is not merged yet, but yeah it will be merged.

So before working on any issue, you should see the messages there in that issue that is whether someone is working on it or not such that no one's work should be wasted

If you don't know which issues to contribute, either find it on your own like we did or you can ask from @CulturalProfessor

**Comment by smitjiwani** [comment]
There is no need to get defensive, we are all here to learn, that is what open-source is about. As far as I understand it is a good first issue and no one has been assigned to it. 

> @smitjiwani For your kind info, let me tell you i have been assigned this issue and i have already completed it some days before. But not created a pr for it because it was a continuation to the this pr #46 . So when this #46 pr will be merged then only i can create the pr for delete command so that no issue arises. As @CulturalProfessor is busy, thats why the above pr is not merged yet, but yeah it will be merged.
> 
> So before working on any issue, you should see the messages there in that issue that is whether someone is working on it or not such that no one's work should be wasted
> 
> If you don't know which issues to contribute, either find it on your own like we did or you can ask from @CulturalProfessor

**Comment by CulturalProfessor** [comment]
@Sumitwarrior7 this kind of behaviour is not good for OSS so refrain from it .

> @smitjiwani For your kind info, let me tell you i have been assigned this issue and i have already completed it some days before. But not created a pr for it because it was a continuation to the this pr #46 . So when this #46 pr will be merged then only i can create the pr for delete command so that no issue arises. As @CulturalProfessor is busy, thats why the above pr is not merged yet, but yeah it will be merged.
> 
> So before working on any issue, you should see the messages there in that issue that is whether someone is working on it or not such that no one's work should be wasted
> 
> If you don't know which issues to contribute, either find it on your own like we did or you can ask from @CulturalProfessor

**Comment by Sumitwarrior7** [comment]
yeah, i thought of it and realized that i was wrong, so sorry for that.

**Pull request closed without merging**
