### PR TITLE
Public/Private status changing messages updated

### PR DESCRIPTION
**Pull request by Sumitwarrior7**
While changing the status of boards, the message displayed now conatins boardname as well

### CODE REVIEW

**Comment by Sumitwarrior7** [comment]
Changing Public Board to Private :-

Earlier :

Screenshot from 2024-01-07 19-28-27

After :

Screenshot from 2024-01-07 19-29-22

**Comment by Sumitwarrior7** [comment]
Changing Private board to Public :-

Earlier :

Screenshot from 2024-01-07 19-32-00

After:

Screenshot from 2024-01-07 19-32-42

**Comment by Sumitwarrior7** [comment]
Please tell if any changes are required @CulturalProfessor

**Comment by CulturalProfessor** [comment]
> Please tell if any changes are required @CulturalProfessor

LGTM :tada:

**Pull request merged**
