### PR TITLE
Feat: Create command is implemented

### PR DESCRIPTION
**Pull request by Sumitwarrior7**
Changed the command :-
to    **/whiteboard create <whiteboard_name>**
from **/whiteboard new**

This allow users to name their whiteboards during creation. If no name is given, it defaults to creating an Untitled whiteboard

Closes: #49 

Video Reference:

https://github.com/RocketChat/Apps.Whiteboard/assets/108853577/7402e457-1389-472c-a3e5-63fc16d909d5

### CODE REVIEW

**Comment by Sumitwarrior7** [comment]
If you will try to create new board with the name which is already there in the room, then it will display the following message :

Screenshot from 2023-12-28 14-21-27

**Comment by Sumitwarrior7** [comment]
If any changes are needed, please let me know @CulturalProfessor

**Comment by CulturalProfessor** [comment]
@Sumitwarrior7 for getting arguments from commands use SlashcommandContext , see here how it's used in notion app https://github.com/RocketChat/Apps.Notion/blob/main/src/commands/NotionCommand.ts#L24C6-L24C7

**Comment by Sumitwarrior7** [comment]
Ok

**Comment by Sumitwarrior7** [comment]
Can you explain "in text add Whiteboard also" @CulturalProfessor

**Comment by CulturalProfessor** [comment]
> Can you explain "in text add Whiteboard also" @CulturalProfessor

the text should be "${board} Whiteboard by ${user}"

**Comment by Sumitwarrior7** [comment]
Please tell if any changes are required @CulturalProfessor

**Comment by CulturalProfessor** [comment]
@Sumitwarrior7 why have you made changes in sidebar.tsx also

**Comment by Sumitwarrior7** [comment]
Actually I was seeing sidebar.tsx file and I saved the file, so it linted the file that's why this file changed, you can see the file there is no significant changes just little formatting and extra commas nothing more than that
@CulturalProfessor

**Comment by CulturalProfessor** [comment]
@Sumitwarrior7 remove changes in sidebar.tsx, we can add a lint file and script also for consistent formatting

**Comment by Sumitwarrior7** [comment]
ok

**Comment by Sumitwarrior7** [comment]
Done @CulturalProfessor

**Comment by CulturalProfessor** [comment]
> Done @CulturalProfessor

let's merge it

**Pull request merged**
