### PR TITLE
[ Feat ] : List command 

### LINKED ISSUE #28: List whiteboards slash command
A formatted list output for all the whiteboards created similar to **ls** command

### PR DESCRIPTION
**Pull request by brf153**
closes #28 

Screenshot from 2023-12-08 08-05-58

### CODE REVIEW

**Comment by CulturalProfessor** [comment]
@brf153 hey can you show and test if this works even if we have changed boards name ?

**Comment by brf153** [comment]
@CulturalProfessor I was not able to change the board name..Yes, it should get all the boards..I made a new association in which I passed MISC "board" .. it was returning the ids of the boards present in the database. Then I just mapped those ids with getBoardDetails to extract their titles.. but the thing is that in the real world, I think when the users make lots of boards then all of those boards will be shown in the list.. I think we will have to add a search functionality or filter the boards in some way such that we get the boards that belong to either the user or the room or some sort of time range(for example boards made within 1 hour)..by the way, what is a message as a notification? How will I implement this?

**Comment by CulturalProfessor** [comment]
> @CulturalProfessor I was not able to change the board name..Yes, it should get all the boards..I made a new association in which I passed MISC "board" .. it was returning the ids of the boards present in the database. Then I just mapped those ids with getBoardDetails to extract their titles.. but the thing is that in the real world, I think when the users make lots of boards then all of those boards will be shown in the list.. I think we will have to add a search functionality or filter the boards in some way such that we get the boards that belong to either the user or the room or some sort of time range(for example boards made within 1 hour)..by the way, what is a message as a notification? How will I implement this?

@brf153 for message as a notificationsearch sendNotification function for the implementation, it will be a bit complex but we can add second parameter in slashcommands to filter boards by whatever query we want like time . But for now let's add another association of room so it doesn't gives us other room's boards .

**Comment by brf153** [comment]
@CulturalProfessor can you please check whether the sendNotification is working? Cause it is not working in my system. It might happen because I am not getting system notifications for some unknown reason in Ubuntu 22.04. Please help me with this.

**Comment by brf153** [comment]
Also, it gives the board names of all the boards created in all of the rocket chat. Should I limit it to a certain room such that the boards created in a room would only be available?

**Comment by brf153** [comment]
@CulturalProfessor in my system the notifyRoom works correctly but notifyUser does not send any notification

**Comment by CulturalProfessor** [comment]
> @CulturalProfessor in my system the notifyRoom works correctly but notifyUser does not send any notification

@brf153 can you check if the user value you are passing not is not undefined , try to add some logs for debugging?

**Comment by brf153** [comment]
@CulturalProfessor I have checked the user value. It is correct.

**Comment by brf153** [comment]
@CulturalProfessor should I add modify the code such that we see the boards of a certain room only?

**Comment by CulturalProfessor** [comment]
> @CulturalProfessor should I add modify the code such that we see the boards of a certain room only?

yeah it won't be a useful feature if we're listing all the boards of user or one thing we can do is list board with the room so it's easier to manage

**Comment by brf153** [comment]
Screenshot from 2023-12-10 12-54-32

**Comment by brf153** [comment]
@CulturalProfessor I think I have made the changes. Also, right now I am using notifyroom function cause the notifyuser was not working in my system. I will check it with another system and let you know whether that function is working or not.

**Comment by brf153** [comment]
Can we merge this pr now?

**Comment by CulturalProfessor** [comment]
@brf153 can you share a video of the whole working feature displaying if boards of other rooms are displayed are not, try by creating more channels like general

**Comment by brf153** [comment]
@CulturalProfessor sure

**Comment by brf153** [comment]
[Screencast from 11-12-23 07:50:55 PM IST.webm](https://github.com/RocketChat/Apps.Whiteboard/assets/107868772/bd3d7d69-8575-462e-8879-de638e4bf26d)

**Comment by CulturalProfessor** [comment]
LGTM , great work @brf153 :tada:

**Pull request merged**
