### PR TITLE
Revert "Feat: Adding search functionality"

### PR DESCRIPTION
**Pull request by CulturalProfessor**
Reverts RocketChat/Apps.Whiteboard#51

### CODE REVIEW

**Comment by brf153** [comment]
@CulturalProfessor I actually checked it. You can actually see it by yourself. When we search the board, I have made the functionality that the board will be rendered. But the board will be a replica of the original board and not the same board. If we make any changes to the replica board then only the original board will get affected. The issue which he is stating is related to name change. When we change name then we expect that the original board's details will be replaced by the new board's details but it was not happening. Rather the new board is stored along with the original board and so two boards were being created. I was working on this issue and thought of fixing it in the next pr.

**Comment by CulturalProfessor** [comment]
no problem make a new pr with those fixed changes as we'll fill up storage too quick if we have double copies each time we search boards

**Comment by brf153** [comment]
So basically should I delete the board which was made earlier and then render the board. For example:-
i) I made a board named bhandari.
ii) I make multiple messages in the room and then try the search whiteboard command again
iii) Now, I should first delete the previous board and then render the board again in the room.
Is this correct?

**Comment by CulturalProfessor** [comment]
> So basically should I delete the board which was made earlier and then render the board. For example:- i) I made a board named bhandari. ii) I make multiple messages in the room and then try the search whiteboard command again iii) Now, I should first delete the previous board and then render the board again in the room. Is this correct?

but this approach will destroy the board as chat message and just create a new message with it's data , search feature would have been useful if we could scroll back to that particular message

**Comment by brf153** [comment]
@CulturalProfessor oki so I will make the functionality that in search command, we will scroll up to the message rather than making new messages to render board data.

**Pull request merged**
